apiVersion: v1
kind: Service
metadata:
  name: lythevine-service
  namespace: rashid
  labels:
    owner: lythevine
    type: service
spec: 
  selector:
    matchLabels:
      owner: lythevine
      type: service
  ports:  
    - port:  8081
      targetPort: 81
      nodePort: 30612
  type: nodePort

  #kubectl apply -f service.yml 
  #kubectl get svc lythevine-service 