apiVersion: v1
kind: Service
metadata:
  name: lythevine-service
  namespace: rashid
  labels:
    owner: lythevine
    type: service
spec: 
  selector:
    matchLabels:
      owner: lythevine
      type: service
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30400
    type: nodePort
    name: http
  - port: 22
    targetPort: 22
    name: ssh
    protocol: TCP    
